>colab에서 작성되었습니다! 

# **모듈, 라이브러리**


In [ ]:
#사용자 정의 모듈
from google.colab import files 
uploaded = files.upload()


Saving my_module.py to my_module.py


In [ ]:
import my_module as m

In [ ]:
ex = m.stock()

객체가 생성되었습니다.


In [ ]:
ex.set_info('셀트리온','068270',181500)

In [ ]:
ex.print_info()

--------------------
 kospi
 종목:  셀트리온
 종목코드:  068270
 주가: 181500원 
--------------------


# **Numpy/Pandas**

**Numpy**

pandas/matplotlib의 기반이 되는 모듈

In [ ]:
import numpy as np 
arr = np.array([1,2,3,4,5])
print(arr)
print(arr.ndim) # 차원 정보
print(arr.shape) #(행,열)을 튜플로 출력

[1 2 3 4 5]
1
(5,)


In [ ]:
#matrix
arr1 = np.array([[1,2,3],[4,5,6]],dtype=np.float64) 
print(arr1)
print(arr1[0,1])
print(arr1.ndim)
print(arr1.shape)

[[1. 2. 3.]
 [4. 5. 6.]]
2.0
2
(2, 3)


**pandas**

데이터 분석 핵심 라이브러리

series -> numpy의 1차원 vector와 유사

dataframe-> numpy의 2차원 matrix와 유사

In [ ]:
import numpy as np 
import pandas as pd 

In [ ]:
#1차원 시리즈
s = pd.Series([1,2,3,4,5], dtype=np.float64) # 인덱스와 값이 같이 출력됨
print(s)
print(s.index) # index만 추출할 수 있음.
print(s.values)

0    1.0
1    2.0
2    3.0
3    4.0
4    5.0
dtype: float64
RangeIndex(start=0, stop=5, step=1)
[1. 2. 3. 4. 5.]


In [ ]:
s = pd.Series([1,2,3,4,5], index=['c','a','d','k','t'] ) #인덱스 정의 가능
print(s)
print(s[0]) #index를 따로 지정해주었을 경우에도 숫자 인덱스를 못쓰는 것 아님.
print(s['c':'d']) #슬라이싱 가능

c    1
a    2
d    3
k    4
t    5
dtype: int64
1
c    1
a    2
d    3
dtype: int64


In [ ]:
#dataframe: 2차원 matrix 형태의 프레임

data ={'5G 섹터':['케이엠더블유','RFHIC','오이솔루션'],
       '종목 코드':['032500','218410','138080'],
       '주가':[56100,34250,34900]}

df = pd.DataFrame(data) # 데이터분석을 위해 프레임을 만듬
display(df)
print(df.shape)


5G 섹터   종목 코드     주가
0  케이엠더블유  032500  56100
1   RFHIC  218410  34250
2   오이솔루션  138080  34900

(3, 3)


>데이터를 가져와서 작업해 보아요!
---

[데이터를 가져오는 대표적인 방법]

 **-원하는 데이터가 담긴 엑셀 파일을 다운**

-금융 데이터 수집 라이브러리 이용(가격 정보)

-웹크롤링






In [ ]:
# 원하는 데이터가 담긴 엑셀 파일 가져오기

from google.colab import files
uploaded = files.upload()

Saving 배당주.xlsx to 배당주 (1).xlsx


In [ ]:
df = pd.read_excel('배당주.xlsx', sheet_name='in')

In [ ]:
display(df.head()) #head() 함수는 위에서부터 5개의 줄 출력

종목코드       종목명    현재가   배당금  배당수익률   배당성향   ROE    PER   PBR
0  '065690       파커스   1490   300  0.201  0.923   5.0   4.58  0.21
1  '041520      이라이콤   2530   400  0.158  0.593   4.0   3.75  0.15
2  '034950    한국기업평가  57500  8618  0.150  1.922  21.0  12.83  2.39
3  '155900    바다로19호   2435   354  0.145  0.727  16.3   5.00  0.81
4  '078020  이베스트투자증권   3400   485  0.143  0.577   8.6   4.04  0.31

**column 단위 데이터 추출**

In [ ]:
print(df['종목명']) # series 형태로 출력

0          파커스
1         이라이콤
2       한국기업평가
3       바다로19호
4     이베스트투자증권
        ...   
95      스카이라이프
96        S&TC
97      미래에셋생명
98       풍산홀딩스
99      인지디스플레
Name: 종목명, Length: 100, dtype: object


In [ ]:
#column 단위 데이터 추출(n개)
df[['종목명','현재가','배당수익률','배당금']]

종목명     현재가  배당수익률    배당금
0        파커스   1,490  20.1%    300
1       이라이콤   2,530  15.8%    400
2     한국기업평가  57,500  15.0%  8,618
3     바다로19호   2,435  14.5%    354
4   이베스트투자증권   3,400  14.3%    485
..       ...     ...    ...    ...
95    스카이라이프   5,150   6.8%    350
96      S&TC  11,800   6.8%    800
97    미래에셋생명   2,510   6.8%    170
98     풍산홀딩스  20,900   6.7%  1,400
99    인지디스플레   1,120   6.7%     75

[100 rows x 4 columns]

**데이터 접근 및 수정**

In [ ]:
df['종목명'][0] = 'vkzjtm'

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


In [ ]:
df['종목명'][0]

'vkzjtm'

In [ ]:
df['종목명'][0]='파커스'

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [ ]:
#list 또는 numpy형식으로 데이터 수정 가능
#문제 상황: 가격 정보를 숫자로 인식하게 하여 연산을 하고 싶은데 현재가에 담긴 데이터로는 바로 처리 어렵다
def data_process(index):
  ind=[]
  ind = list(df[index])

  for i in range(len(df[index])):
    if(ind[i][-1]=='%'):
      ind[i] = float(ind[i].replace('%', ''));
    elif(ind[i][0]=="'"):
      ind[i] = ind[i].replace("'", '')
    else:
      ind[i] = float(ind[i].replace(',', ''))
     
  df[index]=pd.DataFrame(ind)

In [ ]:
data_process('종목코드')

In [ ]:
data_process('현재가')

In [ ]:
data_process('배당금')

In [ ]:
data_process('배당수익률')

In [ ]:
data_process('배당성향')

In [ ]:
df.head()

종목코드       종목명      현재가     배당금  배당수익률   배당성향   ROE    PER   PBR
0  065690       파커스   1490.0   300.0   20.1   92.3   5.0   4.58  0.21
1  041520      이라이콤   2530.0   400.0   15.8   59.3   4.0   3.75  0.15
2  034950    한국기업평가  57500.0  8618.0   15.0  192.2  21.0  12.83  2.39
3  155900    바다로19호   2435.0   354.0   14.5   72.7  16.3   5.00  0.81
4  078020  이베스트투자증권   3400.0   485.0   14.3   57.7   8.6   4.04  0.31

**column 추가/삭제 (+)연산**

In [ ]:
# column 추가
df['신호']= 0

In [ ]:
# column 연산
for i in range(len(df['ROE'])): 
  if(df['ROE'][i]>=float(df['ROE'].mean())) :
        df['신호'][i]=1

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until


In [ ]:
df.head()

종목코드       종목명      현재가     배당금  배당수익률   배당성향   ROE    PER   PBR  신호
0  065690       파커스   1490.0   300.0   20.1   92.3   5.0   4.58  0.21   0
1  041520      이라이콤   2530.0   400.0   15.8   59.3   4.0   3.75  0.15   0
2  034950    한국기업평가  57500.0  8618.0   15.0  192.2  21.0  12.83  2.39   1
3  155900    바다로19호   2435.0   354.0   14.5   72.7  16.3   5.00  0.81   1
4  078020  이베스트투자증권   3400.0   485.0   14.3   57.7   8.6   4.04  0.31   0

In [ ]:
# column 삭제
df['실수']= 0
df.head()

종목코드       종목명      현재가     배당금  배당수익률   배당성향   ROE    PER   PBR  신호  실수
0  065690       파커스   1490.0   300.0   20.1   92.3   5.0   4.58  0.21   0   0
1  041520      이라이콤   2530.0   400.0   15.8   59.3   4.0   3.75  0.15   0   0
2  034950    한국기업평가  57500.0  8618.0   15.0  192.2  21.0  12.83  2.39   1   0
3  155900    바다로19호   2435.0   354.0   14.5   72.7  16.3   5.00  0.81   1   0
4  078020  이베스트투자증권   3400.0   485.0   14.3   57.7   8.6   4.04  0.31   0   0

In [ ]:
# keyword del 사용
del df['실수']
df.head()

종목코드       종목명      현재가     배당금  배당수익률   배당성향   ROE    PER   PBR  신호
0  065690       파커스   1490.0   300.0   20.1   92.3   5.0   4.58  0.21   0
1  041520      이라이콤   2530.0   400.0   15.8   59.3   4.0   3.75  0.15   0
2  034950    한국기업평가  57500.0  8618.0   15.0  192.2  21.0  12.83  2.39   1
3  155900    바다로19호   2435.0   354.0   14.5   72.7  16.3   5.00  0.81   1
4  078020  이베스트투자증권   3400.0   485.0   14.3   57.7   8.6   4.04  0.31   0

In [ ]:
df['실수']= 0
new_df= df.drop('실수', axis=1, inplace= False) #True 설정 시 원본까지 변경
new_df.head()

종목코드       종목명      현재가     배당금  배당수익률   배당성향   ROE    PER   PBR  신호
0  065690       파커스   1490.0   300.0   20.1   92.3   5.0   4.58  0.21   0
1  041520      이라이콤   2530.0   400.0   15.8   59.3   4.0   3.75  0.15   0
2  034950    한국기업평가  57500.0  8618.0   15.0  192.2  21.0  12.83  2.39   1
3  155900    바다로19호   2435.0   354.0   14.5   72.7  16.3   5.00  0.81   1
4  078020  이베스트투자증권   3400.0   485.0   14.3   57.7   8.6   4.04  0.31   0

In [ ]:
df.head()

종목코드       종목명      현재가     배당금  배당수익률   배당성향   ROE    PER   PBR  신호  실수
0  065690       파커스   1490.0   300.0   20.1   92.3   5.0   4.58  0.21   0   0
1  041520      이라이콤   2530.0   400.0   15.8   59.3   4.0   3.75  0.15   0   0
2  034950    한국기업평가  57500.0  8618.0   15.0  192.2  21.0  12.83  2.39   1   0
3  155900    바다로19호   2435.0   354.0   14.5   72.7  16.3   5.00  0.81   1   0
4  078020  이베스트투자증권   3400.0   485.0   14.3   57.7   8.6   4.04  0.31   0   0

**row 기준 데이터 접근/추출**

In [ ]:
del df['실수']
#추출/접근: df.loc[인덱스]
df.loc[1]

종목코드     041520
종목명        이라이콤
현재가        2530
배당금         400
배당수익률      15.8
배당성향       59.3
ROE           4
PER        3.75
PBR        0.15
신호            0
Name: 1, dtype: object

In [ ]:
df.index=df['종목코드']
del df['종목코드']
df.head()

종목명      현재가     배당금  배당수익률   배당성향   ROE    PER   PBR  신호
종목코드                                                                  
065690       파커스   1490.0   300.0   20.1   92.3   5.0   4.58  0.21   0
041520      이라이콤   2530.0   400.0   15.8   59.3   4.0   3.75  0.15   0
034950    한국기업평가  57500.0  8618.0   15.0  192.2  21.0  12.83  2.39   1
155900    바다로19호   2435.0   354.0   14.5   72.7  16.3   5.00  0.81   1
078020  이베스트투자증권   3400.0   485.0   14.3   57.7   8.6   4.04  0.31   0

In [ ]:
df.loc["065690"]


종목명       파커스
현재가      1490
배당금       300
배당수익률    20.1
배당성향     92.3
ROE         5
PER      4.58
PBR      0.21
신호          0
Name: 065690, dtype: object

In [ ]:
df.iloc[0]

종목명      파커스는_아님
현재가         1490
배당금          300
배당수익률       20.1
배당성향        92.3
ROE            5
PER         4.58
PBR         0.21
신호             0
Name: 065690, dtype: object

In [ ]:
#슬라이싱 가능
df.loc["065690":"078020"]

종목명      현재가     배당금  배당수익률   배당성향   ROE    PER   PBR  신호
종목코드                                                                  
065690       파커스   1490.0   300.0   20.1   92.3   5.0   4.58  0.21   0
041520      이라이콤   2530.0   400.0   15.8   59.3   4.0   3.75  0.15   0
034950    한국기업평가  57500.0  8618.0   15.0  192.2  21.0  12.83  2.39   1
155900    바다로19호   2435.0   354.0   14.5   72.7  16.3   5.00  0.81   1
078020  이베스트투자증권   3400.0   485.0   14.3   57.7   8.6   4.04  0.31   0

In [ ]:
df.loc["065690":"078020","배당금"]

종목코드
065690     300.0
041520     400.0
034950    8618.0
155900     354.0
078020     485.0
Name: 배당금, dtype: float64

In [ ]:
df.loc["065690":"078020",["배당금","배당수익률"]] # 2개 이상의 column 

배당금  배당수익률
종목코드                 
065690   300.0   20.1
041520   400.0   15.8
034950  8618.0   15.0
155900   354.0   14.5
078020   485.0   14.3

In [ ]:
df.loc["065690":"078020","현재가":"배당수익률"]

현재가     배당금  배당수익률
종목코드                          
065690   1490.0   300.0   20.1
041520   2530.0   400.0   15.8
034950  57500.0  8618.0   15.0
155900   2435.0   354.0   14.5
078020   3400.0   485.0   14.3

**row 기준 데이터 추가**

In [ ]:
#인덱스에 없는 값을 선언하면 추가해주고
#인덱스에 있는 값에 대해 무언가를 정의하면 수정해줌

df.loc["아이쿠",:] = ['실수했네',898,2,4,4,4,32,5,3]
df.loc["065690",'종목명'] = '파커스는_아님'

In [ ]:
df

종목명      현재가     배당금  배당수익률   배당성향   ROE    PER   PBR   신호
종목코드                                                                   
065690   파커스는_아님   1490.0   300.0   20.1   92.3   5.0   4.58  0.21  0.0
041520      이라이콤   2530.0   400.0   15.8   59.3   4.0   3.75  0.15  0.0
034950    한국기업평가  57500.0  8618.0   15.0  192.2  21.0  12.83  2.39  1.0
155900    바다로19호   2435.0   354.0   14.5   72.7  16.3   5.00  0.81  1.0
078020  이베스트투자증권   3400.0   485.0   14.3   57.7   8.6   4.04  0.31  0.0
...          ...      ...     ...    ...    ...   ...    ...   ...  ...
100840      S&TC  11800.0   800.0    6.8   38.9   6.5   5.73  0.35  0.0
085620    미래에셋생명   2510.0   170.0    6.8   30.8   5.2   4.54  0.24  0.0
005810     풍산홀딩스  20900.0  1400.0    6.7   45.7   3.4   6.82  0.22  0.0
037330    인지디스플레   1120.0    75.0    6.7   28.2   6.6   4.21  0.27  0.0
아이쿠         실수했네    898.0     2.0    4.0    4.0   4.0  32.00  5.00  3.0

[101 rows x 9 columns]

**row 기준 데이터 삭제**

In [ ]:
test_df=df

In [ ]:
test_df.drop("아이쿠",axis=0)

종목명      현재가     배당금  배당수익률   배당성향   ROE    PER   PBR   신호
종목코드                                                                   
065690   파커스는_아님   1490.0   300.0   20.1   92.3   5.0   4.58  0.21  0.0
041520      이라이콤   2530.0   400.0   15.8   59.3   4.0   3.75  0.15  0.0
034950    한국기업평가  57500.0  8618.0   15.0  192.2  21.0  12.83  2.39  1.0
155900    바다로19호   2435.0   354.0   14.5   72.7  16.3   5.00  0.81  1.0
078020  이베스트투자증권   3400.0   485.0   14.3   57.7   8.6   4.04  0.31  0.0
...          ...      ...     ...    ...    ...   ...    ...   ...  ...
053210    스카이라이프   5150.0   350.0    6.8   30.7   8.0   4.51  0.35  0.0
100840      S&TC  11800.0   800.0    6.8   38.9   6.5   5.73  0.35  0.0
085620    미래에셋생명   2510.0   170.0    6.8   30.8   5.2   4.54  0.24  0.0
005810     풍산홀딩스  20900.0  1400.0    6.7   45.7   3.4   6.82  0.22  0.0
037330    인지디스플레   1120.0    75.0    6.7   28.2   6.6   4.21  0.27  0.0

[100 rows x 9 columns]

In [ ]:
test_df.drop(["아이쿠","065690"]) #여러 개 삭제

종목명      현재가     배당금  배당수익률   배당성향   ROE    PER   PBR   신호
종목코드                                                                   
041520      이라이콤   2530.0   400.0   15.8   59.3   4.0   3.75  0.15  0.0
034950    한국기업평가  57500.0  8618.0   15.0  192.2  21.0  12.83  2.39  1.0
155900    바다로19호   2435.0   354.0   14.5   72.7  16.3   5.00  0.81  1.0
078020  이베스트투자증권   3400.0   485.0   14.3   57.7   8.6   4.04  0.31  0.0
225190     삼양옵틱스   7900.0  1100.0   13.9   88.3  34.7   6.34  2.19  1.0
...          ...      ...     ...    ...    ...   ...    ...   ...  ...
053210    스카이라이프   5150.0   350.0    6.8   30.7   8.0   4.51  0.35  0.0
100840      S&TC  11800.0   800.0    6.8   38.9   6.5   5.73  0.35  0.0
085620    미래에셋생명   2510.0   170.0    6.8   30.8   5.2   4.54  0.24  0.0
005810     풍산홀딩스  20900.0  1400.0    6.7   45.7   3.4   6.82  0.22  0.0
037330    인지디스플레   1120.0    75.0    6.7   28.2   6.6   4.21  0.27  0.0

[99 rows x 9 columns]

In [ ]:
#원상태로 복구
df.loc["065690",'종목명'] = '파커스'


**dataframe 결측값 제어**(자주 쓰임/뒤에서 다룰 예정)

만약 dataframe에 nan값과 같은 결측값이 있다면? 

df.dropna() 
inplace =True 설정이 되어야 원본 변경
how='all'을 인자로 넣어주면 모든 column 값이 nan일 때만 행 삭제

**dataframe 분석**

In [ ]:
#describe() 연산가능한 값이 있는 column 에 대해 다음과 같은 값들 제시
display(df.describe())

현재가           배당금  ...         PBR          신호
count     100.000000    100.000000  ...  100.000000  100.000000
mean    19224.800000   1621.050000  ...    0.480700    0.400000
std     42288.984637   3529.755989  ...    0.463215    0.492366
min       775.000000     75.000000  ...    0.070000    0.000000
25%      2338.750000    200.000000  ...    0.227500    0.000000
50%      4815.000000    400.000000  ...    0.355000    0.000000
75%     11387.500000    950.000000  ...    0.490000    1.000000
max    221000.000000  19000.000000  ...    2.890000    1.000000

[8 rows x 8 columns]

In [ ]:
#개별 column에 대해서는 다음과 같이 메소드 활용
print(df['현재가'].mean())
print(df['현재가'].std())
print(df['현재가'].min())
print(df['현재가'].max())

19224.8
42288.98463733272
775.0
221000.0


In [ ]:
#정렬(오름차순과 내림차순)
df.sort_values(by='배당수익률', ascending = True)

종목명      현재가     배당금  배당수익률   배당성향   ROE    PER   PBR   신호
종목코드                                                                   
037330    인지디스플레   1120.0    75.0    6.7   28.2   6.6   4.21  0.27  0.0
005810     풍산홀딩스  20900.0  1400.0    6.7   45.7   3.4   6.82  0.22  0.0
100840      S&TC  11800.0   800.0    6.8   38.9   6.5   5.73  0.35  0.0
094970      제이엠티   1460.0   100.0    6.8   15.6  21.7   2.28  0.44  1.0
225330    씨엠에스에듀   3800.0   260.0    6.8   93.5  12.3  13.67  1.63  1.0
...          ...      ...     ...    ...    ...   ...    ...   ...  ...
078020  이베스트투자증권   3400.0   485.0   14.3   57.7   8.6   4.04  0.31  0.0
155900    바다로19호   2435.0   354.0   14.5   72.7  16.3   5.00  0.81  1.0
034950    한국기업평가  57500.0  8618.0   15.0  192.2  21.0  12.83  2.39  1.0
041520      이라이콤   2530.0   400.0   15.8   59.3   4.0   3.75  0.15  0.0
065690       파커스   1490.0   300.0   20.1   92.3   5.0   4.58  0.21  0.0

[100 rows x 9 columns]

In [ ]:
df.sort_values(by='현재가', ascending = False)

종목명       현재가      배당금  배당수익률   배당성향   ROE    PER   PBR   신호
종목코드                                                                    
002960    한국쉘석유  221000.0  19000.0    8.6   99.0  25.1  11.51  2.89  1.0
002270     롯데푸드  219500.0  15000.0    6.8   39.9   6.3   5.84  0.30  0.0
267250  현대중공업지주  183000.0  18500.0   10.1  112.2   3.5  11.10  0.36  0.0
011170    롯데케미칼  147500.0  10500.0    7.1   22.8  13.0   3.20  0.40  1.0
005490    POSCO  144500.0  10000.0    6.9   47.5   4.2   6.87  0.27  0.0
...         ...       ...      ...    ...    ...   ...    ...   ...  ...
039240     경남스틸    1100.0     90.0    8.2   48.5   NaN   5.93  0.32  0.0
000370   한화손해보험    1025.0    130.0   12.7   18.6   6.3   1.46  0.08  0.0
088350     한화생명     958.0    100.0   10.4   20.9   4.2   2.00  0.07  0.0
127710    아시아경제     947.0     80.0    8.4    7.0  31.1   0.83  0.22  1.0
002870     신풍제지     775.0     80.0   10.3   32.0  18.0   3.10  0.45  1.0

[100 rows x 9 columns]

그 외

**공분산** : 두개의 확률변수에 대한 관계를 보여주는 값, x가 변할 때 y가 변하는 정도를 나타내며, 서로 아무런 관련이 없는 독립이면 0

np.cov(dataframe['column명','column명']

또는

dataframe.['column명'].cov(dataframe.['column명'])


 **상관계수**: 하나의 변수가 변화할 때, 다른 변수가 변화하는 정도 , -1과 1 사이의 실수값을 가짐

dataframe.corr()


In [ ]:
#퀴즈: 신호가 1인 종목들만 추출해봅시다

sort_df=df.sort_values(by='신호', ascending = False)

for i in range(len(sort_df['신호'])):
    if(sort_df['신호'][i]==0):
      x = i
      break
 
sig_df= sort_df.iloc[:x] 
sig_df

**dataframe끼리 합치기**- concat, merge,join 등이 있음.

In [ ]:
a= sig_df.iloc[:5]

In [ ]:
b=sig_df.iloc[7:9]

In [ ]:
c=pd.concat([a,b],axis=0)
c

종목명      현재가     배당금  배당수익률  배당성향   ROE   PER   PBR   신호
종목코드                                                                
138040  메리츠금융지주   6540.0   470.0    7.2  21.1  13.9  2.93  0.37  1.0
000060    메리츠화재   9900.0   820.0    8.3  39.3  11.6  4.74  0.49  1.0
011560    세보엠이씨   3765.0   300.0    8.0  14.5  14.5  1.82  0.24  1.0
005830   DB손해보험  28600.0  2000.0    7.0  26.6  11.0  3.80  0.39  1.0
035000      지투알   3560.0   250.0    7.0  27.1  12.1  3.86  0.43  1.0
034830   한국토지신탁   1560.0   110.0    7.1  16.6  21.8  2.36  0.47  1.0
046110   한일네트웍스   2895.0   230.0    7.9  39.0  10.9  4.92  0.51  1.0

In [ ]:
d= c[['종목명','배당수익률']]

In [ ]:
e=c['ROE']

In [ ]:
f=c=pd.concat([d,e],axis=1)
f

종목명  배당수익률   ROE
종목코드                        
138040  메리츠금융지주    7.2  13.9
000060    메리츠화재    8.3  11.6
011560    세보엠이씨    8.0  14.5
005830   DB손해보험    7.0  11.0
035000      지투알    7.0  12.1
034830   한국토지신탁    7.1  21.8
046110   한일네트웍스    7.9  10.9